// <auto-generated> Regenerate with: python3 gen_slots.py 63 Components.cs </auto-generated>
using System;
using System.Collections.Generic;
using Friflo.Engine.ECS;

// ReSharper disable UnusedMember.Global
// ReSharper disable once CheckNamespace
namespace Tests.OwnerMask {

internal interface ISlotValue  { int    Value  { get; set; } }
internal interface ISlotTarget { Entity Target { get; set; } }

internal struct OwnerSlot01 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot02 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot03 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot04 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot05 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot06 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot07 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot08 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot09 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot10 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot11 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot12 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot13 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot14 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot15 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot16 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot17 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot18 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot19 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot20 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot21 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot22 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot23 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot24 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot25 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot26 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot27 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot28 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot29 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot30 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot31 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot32 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot33 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot34 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot35 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot36 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot37 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot38 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot39 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot40 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot41 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot42 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot43 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot44 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot45 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot46 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot47 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot48 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot49 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot50 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot51 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot52 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot53 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot54 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot55 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot56 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot57 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot58 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot59 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}
internal struct OwnerSlot60 : ILinkRelation, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetRelationKey() => slotTarget;
}
internal struct OwnerSlot61 : IIndexedComponent<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetIndexedValue() => slotValue;
}
internal struct OwnerSlot62 : IRelation<int>, ISlotValue {
    public int slotValue;
    public int Value { get => slotValue; set => slotValue = value; }
    public int GetRelationKey() => slotValue;
}
internal struct OwnerSlot63 : ILinkComponent, ISlotTarget {
    public Entity slotTarget;
    public Entity Target { get => slotTarget; set => slotTarget = value; }
    public Entity GetIndexedValue() => slotTarget;
}

internal static class SlotProbes
{
    private static readonly Dictionary<Type, ISlotProbe> Map = new Dictionary<Type, ISlotProbe>();

    public static ISlotProbe Get(Type type) => Map[type];

    public static bool TryGet(Type type, out ISlotProbe probe) => Map.TryGetValue(type, out probe);

    private static void Add(ISlotProbe probe) => Map[probe.Type] = probe;

    static SlotProbes()
    {
        Add(new IndexedProbe<OwnerSlot01>());
        Add(new RelationProbe<OwnerSlot02>());
        Add(new LinkComponentProbe<OwnerSlot03>());
        Add(new LinkRelationProbe<OwnerSlot04>());
        Add(new IndexedProbe<OwnerSlot05>());
        Add(new RelationProbe<OwnerSlot06>());
        Add(new LinkComponentProbe<OwnerSlot07>());
        Add(new LinkRelationProbe<OwnerSlot08>());
        Add(new IndexedProbe<OwnerSlot09>());
        Add(new RelationProbe<OwnerSlot10>());
        Add(new LinkComponentProbe<OwnerSlot11>());
        Add(new LinkRelationProbe<OwnerSlot12>());
        Add(new IndexedProbe<OwnerSlot13>());
        Add(new RelationProbe<OwnerSlot14>());
        Add(new LinkComponentProbe<OwnerSlot15>());
        Add(new LinkRelationProbe<OwnerSlot16>());
        Add(new IndexedProbe<OwnerSlot17>());
        Add(new RelationProbe<OwnerSlot18>());
        Add(new LinkComponentProbe<OwnerSlot19>());
        Add(new LinkRelationProbe<OwnerSlot20>());
        Add(new IndexedProbe<OwnerSlot21>());
        Add(new RelationProbe<OwnerSlot22>());
        Add(new LinkComponentProbe<OwnerSlot23>());
        Add(new LinkRelationProbe<OwnerSlot24>());
        Add(new IndexedProbe<OwnerSlot25>());
        Add(new RelationProbe<OwnerSlot26>());
        Add(new LinkComponentProbe<OwnerSlot27>());
        Add(new LinkRelationProbe<OwnerSlot28>());
        Add(new IndexedProbe<OwnerSlot29>());
        Add(new RelationProbe<OwnerSlot30>());
        Add(new LinkComponentProbe<OwnerSlot31>());
        Add(new LinkRelationProbe<OwnerSlot32>());
        Add(new IndexedProbe<OwnerSlot33>());
        Add(new RelationProbe<OwnerSlot34>());
        Add(new LinkComponentProbe<OwnerSlot35>());
        Add(new LinkRelationProbe<OwnerSlot36>());
        Add(new IndexedProbe<OwnerSlot37>());
        Add(new RelationProbe<OwnerSlot38>());
        Add(new LinkComponentProbe<OwnerSlot39>());
        Add(new LinkRelationProbe<OwnerSlot40>());
        Add(new IndexedProbe<OwnerSlot41>());
        Add(new RelationProbe<OwnerSlot42>());
        Add(new LinkComponentProbe<OwnerSlot43>());
        Add(new LinkRelationProbe<OwnerSlot44>());
        Add(new IndexedProbe<OwnerSlot45>());
        Add(new RelationProbe<OwnerSlot46>());
        Add(new LinkComponentProbe<OwnerSlot47>());
        Add(new LinkRelationProbe<OwnerSlot48>());
        Add(new IndexedProbe<OwnerSlot49>());
        Add(new RelationProbe<OwnerSlot50>());
        Add(new LinkComponentProbe<OwnerSlot51>());
        Add(new LinkRelationProbe<OwnerSlot52>());
        Add(new IndexedProbe<OwnerSlot53>());
        Add(new RelationProbe<OwnerSlot54>());
        Add(new LinkComponentProbe<OwnerSlot55>());
        Add(new LinkRelationProbe<OwnerSlot56>());
        Add(new IndexedProbe<OwnerSlot57>());
        Add(new RelationProbe<OwnerSlot58>());
        Add(new LinkComponentProbe<OwnerSlot59>());
        Add(new LinkRelationProbe<OwnerSlot60>());
        Add(new IndexedProbe<OwnerSlot61>());
        Add(new RelationProbe<OwnerSlot62>());
        Add(new LinkComponentProbe<OwnerSlot63>());
    }
}

}
