#!/usr/bin/env python3
"""Generate the OwnerSlotNN component types + probe registry for a repro project."""
import sys

count = int(sys.argv[1])
out = sys.argv[2]

KIND_INDEXED, KIND_RELATION, KIND_LINK_COMPONENT, KIND_LINK_RELATION = range(4)

KIND_NAME = {
    KIND_INDEXED:        "Indexed",
    KIND_RELATION:       "Relation",
    KIND_LINK_COMPONENT: "LinkComponent",
    KIND_LINK_RELATION:  "LinkRelation",
}
PROBE = {
    KIND_INDEXED:        "IndexedProbe",
    KIND_RELATION:       "RelationProbe",
    KIND_LINK_COMPONENT: "LinkComponentProbe",
    KIND_LINK_RELATION:  "LinkRelationProbe",
}

decls, probes = [], []
for n in range(1, count + 1):
    name = f"OwnerSlot{n:02d}"
    kind = (n - 1) % 4
    if kind == KIND_INDEXED:
        decls.append(
            f"internal struct {name} : IIndexedComponent<int>, ISlotValue {{\n"
            f"    public int slotValue;\n"
            f"    public int Value {{ get => slotValue; set => slotValue = value; }}\n"
            f"    public int GetIndexedValue() => slotValue;\n"
            f"}}")
    elif kind == KIND_RELATION:
        decls.append(
            f"internal struct {name} : IRelation<int>, ISlotValue {{\n"
            f"    public int slotValue;\n"
            f"    public int Value {{ get => slotValue; set => slotValue = value; }}\n"
            f"    public int GetRelationKey() => slotValue;\n"
            f"}}")
    elif kind == KIND_LINK_COMPONENT:
        decls.append(
            f"internal struct {name} : ILinkComponent, ISlotTarget {{\n"
            f"    public Entity slotTarget;\n"
            f"    public Entity Target {{ get => slotTarget; set => slotTarget = value; }}\n"
            f"    public Entity GetIndexedValue() => slotTarget;\n"
            f"}}")
    else:
        decls.append(
            f"internal struct {name} : ILinkRelation, ISlotTarget {{\n"
            f"    public Entity slotTarget;\n"
            f"    public Entity Target {{ get => slotTarget; set => slotTarget = value; }}\n"
            f"    public Entity GetRelationKey() => slotTarget;\n"
            f"}}")
    probes.append(f"        Add(new {PROBE[kind]}<{name}>());")

header = f"""// <auto-generated> Regenerate with: python3 gen_slots.py {count} Components.cs </auto-generated>
using System;
using System.Collections.Generic;
using Friflo.Engine.ECS;

// ReSharper disable UnusedMember.Global
// ReSharper disable once CheckNamespace
namespace Tests.OwnerMask {{

internal interface ISlotValue  {{ int    Value  {{ get; set; }} }}
internal interface ISlotTarget {{ Entity Target {{ get; set; }} }}

{chr(10).join(decls)}

internal static class SlotProbes
{{
    private static readonly Dictionary<Type, ISlotProbe> Map = new Dictionary<Type, ISlotProbe>();

    public static ISlotProbe Get(Type type) => Map[type];

    public static bool TryGet(Type type, out ISlotProbe probe) => Map.TryGetValue(type, out probe);

    private static void Add(ISlotProbe probe) => Map[probe.Type] = probe;

    static SlotProbes()
    {{
{chr(10).join(probes)}
    }}
}}

}}
"""

with open(out, "w") as f:
    f.write(header)

print(f"wrote {out}: {count} types")
